### PR TITLE
New features

### PR DESCRIPTION
**Pull request by Gecko-Web**
Hi!
Thank you for your work.
I propose some modifications to allow the extension of the class by adding getters for some private properties. (tags, title and description)
I think in some cases it may be useful to access the contents of the tag (see the functions "getTag ()" and "getAllTags ()").
Also, I added a feature to help define multiple tags at once (see the "setTags ()")

Finally, I think it would be interesting to pre-populate some fields if they are already defined in the "tags" array (eg "twitter: title") leaving the possibility to override the field if necessary.
If you are interested, I will propose this change soon.

I hope this helps.

PS: sorry for my broken English... ;)

### CODE REVIEW

**Comment by Gecko-Web** [comment]
Hi!
I just wonder if you have understood how to accept a pull request? Will you accept this one or should I have to create my own repository? 
See you!

**Comment by Puzbie** [comment]
Your changes would change the API, as opposed to add to it. For instance. GetTitle becomes getMetatTitle.

Also, you haven't provided any tests. 

Sorry for the delay in responding. I am busy on a project.

**Comment by Gecko-Web** [comment]
You're right, I will soon propose a new version and thinking about making the tests...
However, the API change ("getMetatTitle" instead of "GetTitle") seems be a good idea in order to add these functionalities while retaining a certain naming convention.

**Comment by Puzbie** [comment]
I don’t like writing tests either. :D

The trouble with getMetaTitle is that it isn’t getting the meta title. There is no meta title. 

Also, using Meta in the method name strikes me as being a bit redundant. It will either be called:

Meta::getMetaTitle

or

$meta->getMetaTitle()

To me, this is excessively repetitive.

**Pull request closed without merging**
